---

- hosts: all
  remote_user: vagrant

  tasks:
    - name: Установка пакетов
      become: true
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose
        - git

    - name: Старт сервиса docker
      become: true
      service:
        name: "docker"
        enabled: yes

    - name: Добавить пользователя vagrant а группу docker
      become: true
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Получение исходников dCV-container
      git:
        clone: yes
        repo: "https://github.com/MaliciousGenius/dCV-container.git"
        dest: "{{ user_home }}/dCV-container"
